// utils/context.tsx
import type { FAQData, TabItem } from './types';

// utils/context.ts
export const tabs: TabItem[] = [
  { title: 'Getting Started', icon: 'rocket' },
  { title: 'Content, Control & Safety', icon: 'shield' },
  { title: 'Credits & Usage', icon: 'handCoins' },
  { title: 'Billing & Account', icon: 'tag' },
];

export const faqData: FAQData = {
  'Getting Started': [
    {
      question: 'What is the Marketing Agent?',
      answer:
        'The Marketing Agent is an AI agent that manages your social media content from start to finish. It creates campaigns, generates posts and captions tailored to your industry and target audience and schedules and publishes content at the best time.',
    },
    {
      question: 'Who is this for?',
      answer:
        'It’s built for founders, small teams, startups and small agencies who handle their own marketing and want to save time creating content.',
    },
    {
      question: 'Do I need marketing experience to use this?',
      answer:
        'No. The Marketing Agent is designed to be simple and beginner-friendly. You don’t need any prior marketing or AI experience.',
    },
    {
      question: 'How do I create my first post?',
      answer:
        'After signing up, enter your website link and the Marketing Agent automatically pulls in your brand details, style and visuals.',
    },
    {
      question: 'What if I don’t have a website yet?',
      answer:
        'That’s fine. You can manually enter your brand description, industry and audience instead.',
    },
    {
      question: 'Which social platforms are supported?',
      answer:
        'Currently, the Marketing Agent supports Instagram, Facebook and LinkedIn.',
    },
    {
      question: 'Can I update or remove my brand information?',
      answer:
        'Yes. You can update your brand details at any time. Your latest brand information will be used going forward and will overwrite previous brand information where applicable.',
    },
    {
      question: 'Can I manage more than one brand?',
      answer:
        'Yes. You can add and manage multiple brands or businesses within the same account.',
    },
    {
      question: 'Can I edit the post before publishing?',
      answer:
        'Yes. You can edit the caption, image, hashtags, date and time before anything is published.',
    },
    {
      question: 'How does the Marketing Agent tailor content to my industry and audience?',
      answer:
        'The Marketing Agent uses your website, brand details and any guidelines you provide to understand your industry and target audience. This ensures posts match your business and messaging.',
    },
    {
      question: 'Does the Marketing Agent create full campaigns or just single posts?',
      answer:
        'It can do both. The Campaign Assistant can generate a single post or create a full campaign with multiple posts planned and scheduled for you.',
    },
    {
      question: 'Does it publish automatically?',
      answer:
        'Yes. Once you approve the content, the Marketing Agent can automatically publish posts on the scheduled date and time. Auto-publishing is optional.',
    },
    {
      question: 'What happens if I don’t like the generated content?',
      answer:
        'You can regenerate the caption, image or both until you’re happy with the result.',
    },
    {
      question: 'Do I own the content that’s generated?',
      answer:
        'Yes. You fully own all content generated by the Marketing Agent and can use it anywhere.',
    },
  ],

  'Content, Control & Safety': [
    {
      question: 'Is my data safe?',
      answer:
        'Yes. Your brand information and generated content are kept private and are not shared with third parties.',
    },
    {
      question: 'Will anything be published without my approval?',
      answer:
        'No. Nothing is published unless you approve it or enable auto-publishing.',
    },
    {
      question: 'Can I pause or delete scheduled posts?',
      answer:
        'Yes. You can pause, edit or delete any scheduled post before it’s published.',
    },
    {
      question: 'Can I reuse generated content?',
      answer:
        'Yes. You can reuse, edit or repurpose any generated content however you like.',
    },
  ],

  'Credits & Usage': [
    {
      question: 'How many credits does one post use?',
      answer:
        'A standard post uses 6 credits. You can view your available credits anytime.',
    },
    {
      question: 'What happens if I regenerate content?',
      answer:
        'Each regeneration uses 2 credits.',
    },
    {
      question: 'How many credits does the AI Campaign Assistant use?',
      answer:
        'Each campaign topic generated by the AI Campaign Assistant uses 2 credits. You can always see your total available credits on your dashboard before generating.',
    },
    {
      question: 'What happens when I run out of credits?',
      answer:
        'Content generation pauses. You can wait for your monthly credits to refresh or purchase Add-On credits.',
    },
    {
      question: 'Do unused credits roll over?',
      answer:
        'No. Monthly credits reset each billing cycle.',
    },
    {
      question: 'What are Add-On credits?',
      answer:
        'Add-On credits are one-time purchases that give you extra content when needed.',
    },
    {
      question: 'Do Add-On credits expire?',
      answer:
        'Add-On credits don’t expire each month. They stay in your account and are valid until you close your account.',
    },
  ],

  'Billing & Account': [
    {
      question: 'What happens if my payment fails?',
      answer:
        'Content generation pauses, but you can still access existing content.',
    },
    {
      question: 'Do you retry failed payments?',
      answer:
        'Yes. If a payment fails, we automatically retry charging your card and notify you to update your payment details.',
    },
    {
      question: 'How do I resume access?',
      answer:
        'Once you update your payment method and the payment succeeds, full access is restored immediately and you can continue generating content.',
    },
    {
      question: 'Will I lose my Add-On credits if a payment fails?',
      answer:
        'No. Any Add-On credits you’ve purchased remain in your account and are not affected by payment failures.',
    },
    {
      question: 'Can I still access my account if payment fails?',
      answer:
        'Yes. You can log in, view your content, and manage your billing. Only new content generation is paused until payment is completed.',
    },
    {
      question: 'Can I cancel my subscription anytime?',
      answer:
        'Yes. You can cancel anytime. Your plan remains active until the end of the billing period.',
    },
    {
      question: 'Is there a long-term contract?',
      answer:
        'No. All plans are subscription-based with no long-term commitment.',
    },
  ],
};